version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running automated tests...
      - npm test

  post_build:
    commands:
      - echo Checking node_modules...
      - ls node_modules | head -10
      
      - echo Creating Lambda deployment package...
      - zip -r app.zip . -x "*.git*" "tests/*" ".env"

      - export BUILD_TIME=$(date +%Y%m%d-%H%M%S)

      - echo Current directory...
      - pwd

      - echo Listing generated files...
      - ls -la

      - echo Creating report package...
      - mkdir report-package

      - echo Copying HTML report...
      - cp jest_html_reporters.html report-package/

      - echo Copying report assets...
      - cp -r jest-html-reporters-attach report-package/

      - echo Uploading QA report package to S3...
      - aws s3 cp report-package s3://ai-qa-build-reports/build-$BUILD_TIME/ --recursive

      - echo Verifying S3 upload...
      - aws s3 ls s3://ai-qa-build-reports/build-$BUILD_TIME/

artifacts:
  files:
    - app.zip