version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running automated tests...
      - npm test

  post_build:
    commands:
      - echo Creating Lambda deployment package...
      - zip -r app.zip . -x "*.git*" "tests/*" ".env"

      - echo Uploading QA report to S3...
      - aws s3 cp jest_html_reporters.html s3://ai-qa-build-reports/build-$BUILD_TIME/

      - echo Uploading report assets...
      - aws s3 cp jest-html-reporters-attach s3://ai-qa-build-reports/build-$BUILD_TIME/jest-html-reporters-attach --recursive

artifacts:
  files:
    - app.zip